//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BilingualProgramType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BilingualProgramType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Student does not participate in the Bilingual Education Program"/>
 *     &lt;enumeration value="Transitional Bilingual/Early Exit"/>
 *     &lt;enumeration value="Transitional Bilingual/Late Exit"/>
 *     &lt;enumeration value="Dual Language Immersion/Two-Way"/>
 *     &lt;enumeration value="Dual Language Immersion/One-Way"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BilingualProgramType")
@XmlEnum
public enum BilingualProgramType {

    @XmlEnumValue("Student does not participate in the Bilingual Education Program")
    STUDENT_DOES_NOT_PARTICIPATE_IN_THE_BILINGUAL_EDUCATION_PROGRAM("Student does not participate in the Bilingual Education Program"),
    @XmlEnumValue("Transitional Bilingual/Early Exit")
    TRANSITIONAL_BILINGUAL_EARLY_EXIT("Transitional Bilingual/Early Exit"),
    @XmlEnumValue("Transitional Bilingual/Late Exit")
    TRANSITIONAL_BILINGUAL_LATE_EXIT("Transitional Bilingual/Late Exit"),
    @XmlEnumValue("Dual Language Immersion/Two-Way")
    DUAL_LANGUAGE_IMMERSION_TWO_WAY("Dual Language Immersion/Two-Way"),
    @XmlEnumValue("Dual Language Immersion/One-Way")
    DUAL_LANGUAGE_IMMERSION_ONE_WAY("Dual Language Immersion/One-Way");
    private final String value;

    BilingualProgramType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BilingualProgramType fromValue(String v) {
        for (BilingualProgramType c: BilingualProgramType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
