//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This entity represents the designation of regularly scheduled series of class meetings at designated times and days of the week.
 * 
 * 
 * <p>Java class for ClassPeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassPeriod">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element name="ClassPeriodName" type="{http://ed-fi.org/0100RFC}ClassPeriodNameType"/>
 *         &lt;element name="MeetingTimes" type="{http://ed-fi.org/0100RFC}MeetingTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BellScheduleReference" type="{http://ed-fi.org/0100RFC}BellScheduleReferenceType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassPeriod", propOrder = {
    "classPeriodName",
    "meetingTimes",
    "bellScheduleReference"
})
public class ClassPeriod
    extends ComplexObjectType
{

    @XmlElement(name = "ClassPeriodName", required = true)
    protected String classPeriodName;
    @XmlElement(name = "MeetingTimes")
    protected List<MeetingTime> meetingTimes;
    @XmlElement(name = "BellScheduleReference", required = true)
    protected BellScheduleReferenceType bellScheduleReference;

    /**
     * Gets the value of the classPeriodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassPeriodName() {
        return classPeriodName;
    }

    /**
     * Sets the value of the classPeriodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassPeriodName(String value) {
        this.classPeriodName = value;
    }

    /**
     * Gets the value of the meetingTimes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meetingTimes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeetingTimes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeetingTime }
     * 
     * 
     */
    public List<MeetingTime> getMeetingTimes() {
        if (meetingTimes == null) {
            meetingTimes = new ArrayList<MeetingTime>();
        }
        return this.meetingTimes;
    }

    /**
     * Gets the value of the bellScheduleReference property.
     * 
     * @return
     *     possible object is
     *     {@link BellScheduleReferenceType }
     *     
     */
    public BellScheduleReferenceType getBellScheduleReference() {
        return bellScheduleReference;
    }

    /**
     * Sets the value of the bellScheduleReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BellScheduleReferenceType }
     *     
     */
    public void setBellScheduleReference(BellScheduleReferenceType value) {
        this.bellScheduleReference = value;
    }

}
