//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides alternative references for competency levels during interchange. Use XML IDREF to reference a course record that is included in the interchange
 * 
 * <p>Java class for CompetencyLevelReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompetencyLevelReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}ReferenceType">
 *       &lt;sequence>
 *         &lt;element name="CompetencyLevelIdentity" type="{http://ed-fi.org/0100RFC}CompetencyLevelIdentityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompetencyLevelReferenceType", propOrder = {
    "competencyLevelIdentity"
})
public class CompetencyLevelReferenceType
    extends ReferenceType
{

    @XmlElement(name = "CompetencyLevelIdentity")
    protected CompetencyLevelIdentityType competencyLevelIdentity;

    /**
     * Gets the value of the competencyLevelIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyLevelIdentityType }
     *     
     */
    public CompetencyLevelIdentityType getCompetencyLevelIdentity() {
        return competencyLevelIdentity;
    }

    /**
     * Sets the value of the competencyLevelIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyLevelIdentityType }
     *     
     */
    public void setCompetencyLevelIdentity(CompetencyLevelIdentityType value) {
        this.competencyLevelIdentity = value;
    }

}
