//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulates the possible attributes that can be used to lookup the identity of discipline incidents.
 * 
 * <p>Java class for DisciplineIncidentIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisciplineIncidentIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationOrgIdentificationCode" type="{http://ed-fi.org/0100RFC}EducationOrgIdentificationCode"/>
 *         &lt;element name="IncidentIdentifier" type="{http://ed-fi.org/0100RFC}IncidentIdentifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisciplineIncidentIdentityType", propOrder = {
    "educationOrgIdentificationCode",
    "incidentIdentifier"
})
public class DisciplineIncidentIdentityType {

    @XmlElement(name = "EducationOrgIdentificationCode", required = true)
    protected EducationOrgIdentificationCode educationOrgIdentificationCode;
    @XmlElement(name = "IncidentIdentifier", required = true)
    protected String incidentIdentifier;

    /**
     * Gets the value of the educationOrgIdentificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link EducationOrgIdentificationCode }
     *     
     */
    public EducationOrgIdentificationCode getEducationOrgIdentificationCode() {
        return educationOrgIdentificationCode;
    }

    /**
     * Sets the value of the educationOrgIdentificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationOrgIdentificationCode }
     *     
     */
    public void setEducationOrgIdentificationCode(EducationOrgIdentificationCode value) {
        this.educationOrgIdentificationCode = value;
    }

    /**
     * Gets the value of the incidentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentIdentifier() {
        return incidentIdentifier;
    }

    /**
     * Sets the value of the incidentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentIdentifier(String value) {
        this.incidentIdentifier = value;
    }

}
