//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisciplineActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisciplineActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Bus suspension"/>
 *     &lt;enumeration value="Change of placement (long-term)"/>
 *     &lt;enumeration value="Change of placement (reassignment), pending an expulsion hearing"/>
 *     &lt;enumeration value="Change of placement (reassignment), resulting from an expulsion hearing"/>
 *     &lt;enumeration value="Change of placement (reassignment), temporary"/>
 *     &lt;enumeration value="Community service"/>
 *     &lt;enumeration value="Conference with and warning to student"/>
 *     &lt;enumeration value="Conference with and warning to student and parent/guardian"/>
 *     &lt;enumeration value="Confiscation of contraband"/>
 *     &lt;enumeration value="Conflict resolution or anger management services mandated"/>
 *     &lt;enumeration value="Corporal punishment"/>
 *     &lt;enumeration value="Counseling mandated"/>
 *     &lt;enumeration value="Demerit"/>
 *     &lt;enumeration value="Detention"/>
 *     &lt;enumeration value="Expulsion recommendation"/>
 *     &lt;enumeration value="Expulsion with services"/>
 *     &lt;enumeration value="Expulsion without services"/>
 *     &lt;enumeration value="Juvenile justice referral"/>
 *     &lt;enumeration value="Law enforcement referral"/>
 *     &lt;enumeration value="Letter of apology"/>
 *     &lt;enumeration value="Loss of privileges"/>
 *     &lt;enumeration value="Physical activity"/>
 *     &lt;enumeration value="Reprimand"/>
 *     &lt;enumeration value="Restitution"/>
 *     &lt;enumeration value="Saturday school"/>
 *     &lt;enumeration value="School probation"/>
 *     &lt;enumeration value="Substance abuse counseling mandated"/>
 *     &lt;enumeration value="Substance abuse treatment mandated"/>
 *     &lt;enumeration value="Suspension after school"/>
 *     &lt;enumeration value="Suspension, in-school"/>
 *     &lt;enumeration value="Suspension, out-of-school, with services"/>
 *     &lt;enumeration value="Suspension, out-of-school, without services"/>
 *     &lt;enumeration value="Unsatisfactory behavior grade"/>
 *     &lt;enumeration value="Work detail"/>
 *     &lt;enumeration value="No action"/>
 *     &lt;enumeration value="Suspension, out of school, greater than 10 consecutive school days"/>
 *     &lt;enumeration value="Suspension, out of school, separate days cumulating to more than 10 school days"/>
 *     &lt;enumeration value="Unilateral removal - weapon incident"/>
 *     &lt;enumeration value="Unilateral removal - drug incident"/>
 *     &lt;enumeration value="Removal by a hearing officer"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Mechanical Restraint"/>
 *     &lt;enumeration value="Physical Restraint"/>
 *     &lt;enumeration value="Seclusion"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisciplineActionType")
@XmlEnum
public enum DisciplineActionType {

    @XmlEnumValue("Bus suspension")
    BUS_SUSPENSION("Bus suspension"),
    @XmlEnumValue("Change of placement (long-term)")
    CHANGE_OF_PLACEMENT_LONG_TERM("Change of placement (long-term)"),
    @XmlEnumValue("Change of placement (reassignment), pending an expulsion hearing")
    CHANGE_OF_PLACEMENT_REASSIGNMENT_PENDING_AN_EXPULSION_HEARING("Change of placement (reassignment), pending an expulsion hearing"),
    @XmlEnumValue("Change of placement (reassignment), resulting from an expulsion hearing")
    CHANGE_OF_PLACEMENT_REASSIGNMENT_RESULTING_FROM_AN_EXPULSION_HEARING("Change of placement (reassignment), resulting from an expulsion hearing"),
    @XmlEnumValue("Change of placement (reassignment), temporary")
    CHANGE_OF_PLACEMENT_REASSIGNMENT_TEMPORARY("Change of placement (reassignment), temporary"),
    @XmlEnumValue("Community service")
    COMMUNITY_SERVICE("Community service"),
    @XmlEnumValue("Conference with and warning to student")
    CONFERENCE_WITH_AND_WARNING_TO_STUDENT("Conference with and warning to student"),
    @XmlEnumValue("Conference with and warning to student and parent/guardian")
    CONFERENCE_WITH_AND_WARNING_TO_STUDENT_AND_PARENT_GUARDIAN("Conference with and warning to student and parent/guardian"),
    @XmlEnumValue("Confiscation of contraband")
    CONFISCATION_OF_CONTRABAND("Confiscation of contraband"),
    @XmlEnumValue("Conflict resolution or anger management services mandated")
    CONFLICT_RESOLUTION_OR_ANGER_MANAGEMENT_SERVICES_MANDATED("Conflict resolution or anger management services mandated"),
    @XmlEnumValue("Corporal punishment")
    CORPORAL_PUNISHMENT("Corporal punishment"),
    @XmlEnumValue("Counseling mandated")
    COUNSELING_MANDATED("Counseling mandated"),
    @XmlEnumValue("Demerit")
    DEMERIT("Demerit"),
    @XmlEnumValue("Detention")
    DETENTION("Detention"),
    @XmlEnumValue("Expulsion recommendation")
    EXPULSION_RECOMMENDATION("Expulsion recommendation"),
    @XmlEnumValue("Expulsion with services")
    EXPULSION_WITH_SERVICES("Expulsion with services"),
    @XmlEnumValue("Expulsion without services")
    EXPULSION_WITHOUT_SERVICES("Expulsion without services"),
    @XmlEnumValue("Juvenile justice referral")
    JUVENILE_JUSTICE_REFERRAL("Juvenile justice referral"),
    @XmlEnumValue("Law enforcement referral")
    LAW_ENFORCEMENT_REFERRAL("Law enforcement referral"),
    @XmlEnumValue("Letter of apology")
    LETTER_OF_APOLOGY("Letter of apology"),
    @XmlEnumValue("Loss of privileges")
    LOSS_OF_PRIVILEGES("Loss of privileges"),
    @XmlEnumValue("Physical activity")
    PHYSICAL_ACTIVITY("Physical activity"),
    @XmlEnumValue("Reprimand")
    REPRIMAND("Reprimand"),
    @XmlEnumValue("Restitution")
    RESTITUTION("Restitution"),
    @XmlEnumValue("Saturday school")
    SATURDAY_SCHOOL("Saturday school"),
    @XmlEnumValue("School probation")
    SCHOOL_PROBATION("School probation"),
    @XmlEnumValue("Substance abuse counseling mandated")
    SUBSTANCE_ABUSE_COUNSELING_MANDATED("Substance abuse counseling mandated"),
    @XmlEnumValue("Substance abuse treatment mandated")
    SUBSTANCE_ABUSE_TREATMENT_MANDATED("Substance abuse treatment mandated"),
    @XmlEnumValue("Suspension after school")
    SUSPENSION_AFTER_SCHOOL("Suspension after school"),
    @XmlEnumValue("Suspension, in-school")
    SUSPENSION_IN_SCHOOL("Suspension, in-school"),
    @XmlEnumValue("Suspension, out-of-school, with services")
    SUSPENSION_OUT_OF_SCHOOL_WITH_SERVICES("Suspension, out-of-school, with services"),
    @XmlEnumValue("Suspension, out-of-school, without services")
    SUSPENSION_OUT_OF_SCHOOL_WITHOUT_SERVICES("Suspension, out-of-school, without services"),
    @XmlEnumValue("Unsatisfactory behavior grade")
    UNSATISFACTORY_BEHAVIOR_GRADE("Unsatisfactory behavior grade"),
    @XmlEnumValue("Work detail")
    WORK_DETAIL("Work detail"),
    @XmlEnumValue("No action")
    NO_ACTION("No action"),
    @XmlEnumValue("Suspension, out of school, greater than 10 consecutive school days")
    SUSPENSION_OUT_OF_SCHOOL_GREATER_THAN_10_CONSECUTIVE_SCHOOL_DAYS("Suspension, out of school, greater than 10 consecutive school days"),
    @XmlEnumValue("Suspension, out of school, separate days cumulating to more than 10 school days")
    SUSPENSION_OUT_OF_SCHOOL_SEPARATE_DAYS_CUMULATING_TO_MORE_THAN_10_SCHOOL_DAYS("Suspension, out of school, separate days cumulating to more than 10 school days"),
    @XmlEnumValue("Unilateral removal - weapon incident")
    UNILATERAL_REMOVAL_WEAPON_INCIDENT("Unilateral removal - weapon incident"),
    @XmlEnumValue("Unilateral removal - drug incident")
    UNILATERAL_REMOVAL_DRUG_INCIDENT("Unilateral removal - drug incident"),
    @XmlEnumValue("Removal by a hearing officer")
    REMOVAL_BY_A_HEARING_OFFICER("Removal by a hearing officer"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Mechanical Restraint")
    MECHANICAL_RESTRAINT("Mechanical Restraint"),
    @XmlEnumValue("Physical Restraint")
    PHYSICAL_RESTRAINT("Physical Restraint"),
    @XmlEnumValue("Seclusion")
    SECLUSION("Seclusion");
    private final String value;

    DisciplineActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisciplineActionType fromValue(String v) {
        for (DisciplineActionType c: DisciplineActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
