//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ESLProgramType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ESLProgramType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Student Does Not Participate"/>
 *     &lt;enumeration value="Content-Based"/>
 *     &lt;enumeration value="Pull-Out"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ESLProgramType")
@XmlEnum
public enum ESLProgramType {

    @XmlEnumValue("Student Does Not Participate")
    STUDENT_DOES_NOT_PARTICIPATE("Student Does Not Participate"),
    @XmlEnumValue("Content-Based")
    CONTENT_BASED("Content-Based"),
    @XmlEnumValue("Pull-Out")
    PULL_OUT("Pull-Out");
    private final String value;

    ESLProgramType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ESLProgramType fromValue(String v) {
        for (ESLProgramType c: ESLProgramType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
