//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncidentCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncidentCategoryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Crime"/>
 *     &lt;enumeration value="State Offense"/>
 *     &lt;enumeration value="School Offense"/>
 *     &lt;enumeration value="School Code of Conduct"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncidentCategoryType")
@XmlEnum
public enum IncidentCategoryType {

    @XmlEnumValue("Crime")
    CRIME("Crime"),
    @XmlEnumValue("State Offense")
    STATE_OFFENSE("State Offense"),
    @XmlEnumValue("School Offense")
    SCHOOL_OFFENSE("School Offense"),
    @XmlEnumValue("School Code of Conduct")
    SCHOOL_CODE_OF_CONDUCT("School Code of Conduct");
    private final String value;

    IncidentCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncidentCategoryType fromValue(String v) {
        for (IncidentCategoryType c: IncidentCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
