//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterpretingServicesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InterpretingServicesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="No interpreting service provided"/>
 *     &lt;enumeration value="Oral Transliteration"/>
 *     &lt;enumeration value="CUED Language Transliteration"/>
 *     &lt;enumeration value="Sign Language Transliteration"/>
 *     &lt;enumeration value="Sign Language Interpreting"/>
 *     &lt;enumeration value="Communication Access Realtime Translation (CART)"/>
 *     &lt;enumeration value="C-Print"/>
 *     &lt;enumeration value="Type Well"/>
 *     &lt;enumeration value="Deaf-Blind Interpreting"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InterpretingServicesType")
@XmlEnum
public enum InterpretingServicesType {

    @XmlEnumValue("No interpreting service provided")
    NO_INTERPRETING_SERVICE_PROVIDED("No interpreting service provided"),
    @XmlEnumValue("Oral Transliteration")
    ORAL_TRANSLITERATION("Oral Transliteration"),
    @XmlEnumValue("CUED Language Transliteration")
    CUED_LANGUAGE_TRANSLITERATION("CUED Language Transliteration"),
    @XmlEnumValue("Sign Language Transliteration")
    SIGN_LANGUAGE_TRANSLITERATION("Sign Language Transliteration"),
    @XmlEnumValue("Sign Language Interpreting")
    SIGN_LANGUAGE_INTERPRETING("Sign Language Interpreting"),
    @XmlEnumValue("Communication Access Realtime Translation (CART)")
    COMMUNICATION_ACCESS_REALTIME_TRANSLATION_CART("Communication Access Realtime Translation (CART)"),
    @XmlEnumValue("C-Print")
    C_PRINT("C-Print"),
    @XmlEnumValue("Type Well")
    TYPE_WELL("Type Well"),
    @XmlEnumValue("Deaf-Blind Interpreting")
    DEAF_BLIND_INTERPRETING("Deaf-Blind Interpreting");
    private final String value;

    InterpretingServicesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterpretingServicesType fromValue(String v) {
        for (InterpretingServicesType c: InterpretingServicesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
