//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulates the possible attributes that can be used to lookup the identity of the Learning Objectives.
 * 
 * <p>Java class for LearningObjectiveIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LearningObjectiveIdentityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}ReferenceType">
 *       &lt;choice>
 *         &lt;element name="LearningObjectiveId" type="{http://ed-fi.org/0100RFC}LearningStandardId"/>
 *         &lt;element name="Objective" type="{http://ed-fi.org/0100RFC}Objective"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearningObjectiveIdentityType", propOrder = {
    "learningObjectiveId",
    "objective"
})
public class LearningObjectiveIdentityType
    extends ReferenceType
{

    @XmlElement(name = "LearningObjectiveId")
    protected String learningObjectiveId;
    @XmlElement(name = "Objective")
    protected String objective;

    /**
     * Gets the value of the learningObjectiveId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLearningObjectiveId() {
        return learningObjectiveId;
    }

    /**
     * Sets the value of the learningObjectiveId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLearningObjectiveId(String value) {
        this.learningObjectiveId = value;
    }

    /**
     * Gets the value of the objective property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjective() {
        return objective;
    }

    /**
     * Sets the value of the objective property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjective(String value) {
        this.objective = value;
    }

}
