//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ed_fi._0100rfc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StudentIdentityTypeHispanicLatinoEthnicity_QNAME = new QName("http://ed-fi.org/0100RFC", "HispanicLatinoEthnicity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ed_fi._0100rfc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link AssessmentIdentityType }
     * 
     */
    public AssessmentIdentityType createAssessmentIdentityType() {
        return new AssessmentIdentityType();
    }

    /**
     * Create an instance of {@link StudentSectionAssociation }
     * 
     */
    public StudentSectionAssociation createStudentSectionAssociation() {
        return new StudentSectionAssociation();
    }

    /**
     * Create an instance of {@link Section504DisabilitiesType }
     * 
     */
    public Section504DisabilitiesType createSection504DisabilitiesType() {
        return new Section504DisabilitiesType();
    }

    /**
     * Create an instance of {@link AssessmentFamilyIdentityType }
     * 
     */
    public AssessmentFamilyIdentityType createAssessmentFamilyIdentityType() {
        return new AssessmentFamilyIdentityType();
    }

    /**
     * Create an instance of {@link StudentSpecialEdProgramAssociation }
     * 
     */
    public StudentSpecialEdProgramAssociation createStudentSpecialEdProgramAssociation() {
        return new StudentSpecialEdProgramAssociation();
    }

    /**
     * Create an instance of {@link WeaponsType }
     * 
     */
    public WeaponsType createWeaponsType() {
        return new WeaponsType();
    }

    /**
     * Create an instance of {@link RaceType }
     * 
     */
    public RaceType createRaceType() {
        return new RaceType();
    }

    /**
     * Create an instance of {@link DisciplineIncidentReferenceType }
     * 
     */
    public DisciplineIncidentReferenceType createDisciplineIncidentReferenceType() {
        return new DisciplineIncidentReferenceType();
    }

    /**
     * Create an instance of {@link Disability }
     * 
     */
    public Disability createDisability() {
        return new Disability();
    }

    /**
     * Create an instance of {@link LearningObjectiveReferenceType }
     * 
     */
    public LearningObjectiveReferenceType createLearningObjectiveReferenceType() {
        return new LearningObjectiveReferenceType();
    }

    /**
     * Create an instance of {@link AssessmentIdentificationCode }
     * 
     */
    public AssessmentIdentificationCode createAssessmentIdentificationCode() {
        return new AssessmentIdentificationCode();
    }

    /**
     * Create an instance of {@link LocalEducationAgency }
     * 
     */
    public LocalEducationAgency createLocalEducationAgency() {
        return new LocalEducationAgency();
    }

    /**
     * Create an instance of {@link LinguisticAccommodationsType }
     * 
     */
    public LinguisticAccommodationsType createLinguisticAccommodationsType() {
        return new LinguisticAccommodationsType();
    }

    /**
     * Create an instance of {@link School }
     * 
     */
    public School createSchool() {
        return new School();
    }

    /**
     * Create an instance of {@link Budget }
     * 
     */
    public Budget createBudget() {
        return new Budget();
    }

    /**
     * Create an instance of {@link AssessmentFamily }
     * 
     */
    public AssessmentFamily createAssessmentFamily() {
        return new AssessmentFamily();
    }

    /**
     * Create an instance of {@link CourseReferenceType }
     * 
     */
    public CourseReferenceType createCourseReferenceType() {
        return new CourseReferenceType();
    }

    /**
     * Create an instance of {@link AssessmentItemIdentityType }
     * 
     */
    public AssessmentItemIdentityType createAssessmentItemIdentityType() {
        return new AssessmentItemIdentityType();
    }

    /**
     * Create an instance of {@link CohortYear }
     * 
     */
    public CohortYear createCohortYear() {
        return new CohortYear();
    }

    /**
     * Create an instance of {@link SectionIdentityType }
     * 
     */
    public SectionIdentityType createSectionIdentityType() {
        return new SectionIdentityType();
    }

    /**
     * Create an instance of {@link TitleIPartASupportServicesType }
     * 
     */
    public TitleIPartASupportServicesType createTitleIPartASupportServicesType() {
        return new TitleIPartASupportServicesType();
    }

    /**
     * Create an instance of {@link BirthData }
     * 
     */
    public BirthData createBirthData() {
        return new BirthData();
    }

    /**
     * Create an instance of {@link StudentESLProgramAssociation }
     * 
     */
    public StudentESLProgramAssociation createStudentESLProgramAssociation() {
        return new StudentESLProgramAssociation();
    }

    /**
     * Create an instance of {@link StaffReferenceType }
     * 
     */
    public StaffReferenceType createStaffReferenceType() {
        return new StaffReferenceType();
    }

    /**
     * Create an instance of {@link CTEProgram }
     * 
     */
    public CTEProgram createCTEProgram() {
        return new CTEProgram();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link TitleIPartAServicesType }
     * 
     */
    public TitleIPartAServicesType createTitleIPartAServicesType() {
        return new TitleIPartAServicesType();
    }

    /**
     * Create an instance of {@link MeetingDaysType }
     * 
     */
    public MeetingDaysType createMeetingDaysType() {
        return new MeetingDaysType();
    }

    /**
     * Create an instance of {@link SpecialEdServicesType }
     * 
     */
    public SpecialEdServicesType createSpecialEdServicesType() {
        return new SpecialEdServicesType();
    }

    /**
     * Create an instance of {@link StudentIdentityType }
     * 
     */
    public StudentIdentityType createStudentIdentityType() {
        return new StudentIdentityType();
    }

    /**
     * Create an instance of {@link StateEducationAgency }
     * 
     */
    public StateEducationAgency createStateEducationAgency() {
        return new StateEducationAgency();
    }

    /**
     * Create an instance of {@link EducationOrganizationCategoriesType }
     * 
     */
    public EducationOrganizationCategoriesType createEducationOrganizationCategoriesType() {
        return new EducationOrganizationCategoriesType();
    }

    /**
     * Create an instance of {@link AccountabilityRating }
     * 
     */
    public AccountabilityRating createAccountabilityRating() {
        return new AccountabilityRating();
    }

    /**
     * Create an instance of {@link AcademicSubjectsType }
     * 
     */
    public AcademicSubjectsType createAcademicSubjectsType() {
        return new AcademicSubjectsType();
    }

    /**
     * Create an instance of {@link BellSchedule }
     * 
     */
    public BellSchedule createBellSchedule() {
        return new BellSchedule();
    }

    /**
     * Create an instance of {@link CourseTranscript }
     * 
     */
    public CourseTranscript createCourseTranscript() {
        return new CourseTranscript();
    }

    /**
     * Create an instance of {@link AcademicWeek }
     * 
     */
    public AcademicWeek createAcademicWeek() {
        return new AcademicWeek();
    }

    /**
     * Create an instance of {@link CourseOffering }
     * 
     */
    public CourseOffering createCourseOffering() {
        return new CourseOffering();
    }

    /**
     * Create an instance of {@link DisciplineAction }
     * 
     */
    public DisciplineAction createDisciplineAction() {
        return new DisciplineAction();
    }

    /**
     * Create an instance of {@link EducationOrgIdentificationCode }
     * 
     */
    public EducationOrgIdentificationCode createEducationOrgIdentificationCode() {
        return new EducationOrgIdentificationCode();
    }

    /**
     * Create an instance of {@link Recognition }
     * 
     */
    public Recognition createRecognition() {
        return new Recognition();
    }

    /**
     * Create an instance of {@link OtherName }
     * 
     */
    public OtherName createOtherName() {
        return new OtherName();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link StaffEducationOrgAssignmentAssociation }
     * 
     */
    public StaffEducationOrgAssignmentAssociation createStaffEducationOrgAssignmentAssociation() {
        return new StaffEducationOrgAssignmentAssociation();
    }

    /**
     * Create an instance of {@link Diploma }
     * 
     */
    public Diploma createDiploma() {
        return new Diploma();
    }

    /**
     * Create an instance of {@link AcademicHonor }
     * 
     */
    public AcademicHonor createAcademicHonor() {
        return new AcademicHonor();
    }

    /**
     * Create an instance of {@link Telephone }
     * 
     */
    public Telephone createTelephone() {
        return new Telephone();
    }

    /**
     * Create an instance of {@link GradingPeriod }
     * 
     */
    public GradingPeriod createGradingPeriod() {
        return new GradingPeriod();
    }

    /**
     * Create an instance of {@link StudentIndicator }
     * 
     */
    public StudentIndicator createStudentIndicator() {
        return new StudentIndicator();
    }

    /**
     * Create an instance of {@link CompetencyLevelReferenceType }
     * 
     */
    public CompetencyLevelReferenceType createCompetencyLevelReferenceType() {
        return new CompetencyLevelReferenceType();
    }

    /**
     * Create an instance of {@link StudentBilingualProgramAssociation }
     * 
     */
    public StudentBilingualProgramAssociation createStudentBilingualProgramAssociation() {
        return new StudentBilingualProgramAssociation();
    }

    /**
     * Create an instance of {@link AccountReferenceType }
     * 
     */
    public AccountReferenceType createAccountReferenceType() {
        return new AccountReferenceType();
    }

    /**
     * Create an instance of {@link CreditsBySubject }
     * 
     */
    public CreditsBySubject createCreditsBySubject() {
        return new CreditsBySubject();
    }

    /**
     * Create an instance of {@link AttendanceEvent }
     * 
     */
    public AttendanceEvent createAttendanceEvent() {
        return new AttendanceEvent();
    }

    /**
     * Create an instance of {@link AssessmentFamilyReferenceType }
     * 
     */
    public AssessmentFamilyReferenceType createAssessmentFamilyReferenceType() {
        return new AssessmentFamilyReferenceType();
    }

    /**
     * Create an instance of {@link CompetencyLevel }
     * 
     */
    public CompetencyLevel createCompetencyLevel() {
        return new CompetencyLevel();
    }

    /**
     * Create an instance of {@link StudentDisciplineIncidentAssociation }
     * 
     */
    public StudentDisciplineIncidentAssociation createStudentDisciplineIncidentAssociation() {
        return new StudentDisciplineIncidentAssociation();
    }

    /**
     * Create an instance of {@link CourseIdentityType }
     * 
     */
    public CourseIdentityType createCourseIdentityType() {
        return new CourseIdentityType();
    }

    /**
     * Create an instance of {@link StudentAssessment }
     * 
     */
    public StudentAssessment createStudentAssessment() {
        return new StudentAssessment();
    }

    /**
     * Create an instance of {@link CourseOfferingIdentityType }
     * 
     */
    public CourseOfferingIdentityType createCourseOfferingIdentityType() {
        return new CourseOfferingIdentityType();
    }

    /**
     * Create an instance of {@link Staff }
     * 
     */
    public Staff createStaff() {
        return new Staff();
    }

    /**
     * Create an instance of {@link CompetencyLevelIdentityType }
     * 
     */
    public CompetencyLevelIdentityType createCompetencyLevelIdentityType() {
        return new CompetencyLevelIdentityType();
    }

    /**
     * Create an instance of {@link GradePointAverage }
     * 
     */
    public GradePointAverage createGradePointAverage() {
        return new GradePointAverage();
    }

    /**
     * Create an instance of {@link RestraintEvent }
     * 
     */
    public RestraintEvent createRestraintEvent() {
        return new RestraintEvent();
    }

    /**
     * Create an instance of {@link Cohort }
     * 
     */
    public Cohort createCohort() {
        return new Cohort();
    }

    /**
     * Create an instance of {@link LearningStandardReferenceType }
     * 
     */
    public LearningStandardReferenceType createLearningStandardReferenceType() {
        return new LearningStandardReferenceType();
    }

    /**
     * Create an instance of {@link Assessment }
     * 
     */
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link OpenStaffPosition }
     * 
     */
    public OpenStaffPosition createOpenStaffPosition() {
        return new OpenStaffPosition();
    }

    /**
     * Create an instance of {@link StudentAssessmentItem }
     * 
     */
    public StudentAssessmentItem createStudentAssessmentItem() {
        return new StudentAssessmentItem();
    }

    /**
     * Create an instance of {@link SectionReferenceType }
     * 
     */
    public SectionReferenceType createSectionReferenceType() {
        return new SectionReferenceType();
    }

    /**
     * Create an instance of {@link FeederSchoolAssociation }
     * 
     */
    public FeederSchoolAssociation createFeederSchoolAssociation() {
        return new FeederSchoolAssociation();
    }

    /**
     * Create an instance of {@link EducationServiceCenter }
     * 
     */
    public EducationServiceCenter createEducationServiceCenter() {
        return new EducationServiceCenter();
    }

    /**
     * Create an instance of {@link StudentGradebookEntry }
     * 
     */
    public StudentGradebookEntry createStudentGradebookEntry() {
        return new StudentGradebookEntry();
    }

    /**
     * Create an instance of {@link StudentIdentificationCode }
     * 
     */
    public StudentIdentificationCode createStudentIdentificationCode() {
        return new StudentIdentificationCode();
    }

    /**
     * Create an instance of {@link StudentParentAssociation }
     * 
     */
    public StudentParentAssociation createStudentParentAssociation() {
        return new StudentParentAssociation();
    }

    /**
     * Create an instance of {@link PostSecondaryEvent }
     * 
     */
    public PostSecondaryEvent createPostSecondaryEvent() {
        return new PostSecondaryEvent();
    }

    /**
     * Create an instance of {@link StudentSectionAssociationReferenceType }
     * 
     */
    public StudentSectionAssociationReferenceType createStudentSectionAssociationReferenceType() {
        return new StudentSectionAssociationReferenceType();
    }

    /**
     * Create an instance of {@link LearningStyles }
     * 
     */
    public LearningStyles createLearningStyles() {
        return new LearningStyles();
    }

    /**
     * Create an instance of {@link EducationalPlansType }
     * 
     */
    public EducationalPlansType createEducationalPlansType() {
        return new EducationalPlansType();
    }

    /**
     * Create an instance of {@link TeacherSectionAssociation }
     * 
     */
    public TeacherSectionAssociation createTeacherSectionAssociation() {
        return new TeacherSectionAssociation();
    }

    /**
     * Create an instance of {@link ScoreResult }
     * 
     */
    public ScoreResult createScoreResult() {
        return new ScoreResult();
    }

    /**
     * Create an instance of {@link DisciplineIncident }
     * 
     */
    public DisciplineIncident createDisciplineIncident() {
        return new DisciplineIncident();
    }

    /**
     * Create an instance of {@link AccountIdentityType }
     * 
     */
    public AccountIdentityType createAccountIdentityType() {
        return new AccountIdentityType();
    }

    /**
     * Create an instance of {@link BellScheduleIdentityType }
     * 
     */
    public BellScheduleIdentityType createBellScheduleIdentityType() {
        return new BellScheduleIdentityType();
    }

    /**
     * Create an instance of {@link StudentProgramAssociation }
     * 
     */
    public StudentProgramAssociation createStudentProgramAssociation() {
        return new StudentProgramAssociation();
    }

    /**
     * Create an instance of {@link StudentSectionAssociationIdentityType }
     * 
     */
    public StudentSectionAssociationIdentityType createStudentSectionAssociationIdentityType() {
        return new StudentSectionAssociationIdentityType();
    }

    /**
     * Create an instance of {@link EmploymentPeriod }
     * 
     */
    public EmploymentPeriod createEmploymentPeriod() {
        return new EmploymentPeriod();
    }

    /**
     * Create an instance of {@link StaffIdentificationCode }
     * 
     */
    public StaffIdentificationCode createStaffIdentificationCode() {
        return new StaffIdentificationCode();
    }

    /**
     * Create an instance of {@link StudentCompetency }
     * 
     */
    public StudentCompetency createStudentCompetency() {
        return new StudentCompetency();
    }

    /**
     * Create an instance of {@link AssessmentPeriodIdentityType }
     * 
     */
    public AssessmentPeriodIdentityType createAssessmentPeriodIdentityType() {
        return new AssessmentPeriodIdentityType();
    }

    /**
     * Create an instance of {@link StudentSupplementalServiceProgramAssociation }
     * 
     */
    public StudentSupplementalServiceProgramAssociation createStudentSupplementalServiceProgramAssociation() {
        return new StudentSupplementalServiceProgramAssociation();
    }

    /**
     * Create an instance of {@link LeaveEvent }
     * 
     */
    public LeaveEvent createLeaveEvent() {
        return new LeaveEvent();
    }

    /**
     * Create an instance of {@link CourseCode }
     * 
     */
    public CourseCode createCourseCode() {
        return new CourseCode();
    }

    /**
     * Create an instance of {@link CalendarDate }
     * 
     */
    public CalendarDate createCalendarDate() {
        return new CalendarDate();
    }

    /**
     * Create an instance of {@link StaffCohortAssociation }
     * 
     */
    public StaffCohortAssociation createStaffCohortAssociation() {
        return new StaffCohortAssociation();
    }

    /**
     * Create an instance of {@link MeetingTime }
     * 
     */
    public MeetingTime createMeetingTime() {
        return new MeetingTime();
    }

    /**
     * Create an instance of {@link CourseOfferingReferenceType }
     * 
     */
    public CourseOfferingReferenceType createCourseOfferingReferenceType() {
        return new CourseOfferingReferenceType();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link SessionIdentityType }
     * 
     */
    public SessionIdentityType createSessionIdentityType() {
        return new SessionIdentityType();
    }

    /**
     * Create an instance of {@link AssessmentPeriod }
     * 
     */
    public AssessmentPeriod createAssessmentPeriod() {
        return new AssessmentPeriod();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link AssessmentReferenceType }
     * 
     */
    public AssessmentReferenceType createAssessmentReferenceType() {
        return new AssessmentReferenceType();
    }

    /**
     * Create an instance of {@link LanguagesType }
     * 
     */
    public LanguagesType createLanguagesType() {
        return new LanguagesType();
    }

    /**
     * Create an instance of {@link BellScheduleReferenceType }
     * 
     */
    public BellScheduleReferenceType createBellScheduleReferenceType() {
        return new BellScheduleReferenceType();
    }

    /**
     * Create an instance of {@link GradingPeriodReferenceType }
     * 
     */
    public GradingPeriodReferenceType createGradingPeriodReferenceType() {
        return new GradingPeriodReferenceType();
    }

    /**
     * Create an instance of {@link ContractedStaff }
     * 
     */
    public ContractedStaff createContractedStaff() {
        return new ContractedStaff();
    }

    /**
     * Create an instance of {@link LearningStandardIdentityType }
     * 
     */
    public LearningStandardIdentityType createLearningStandardIdentityType() {
        return new LearningStandardIdentityType();
    }

    /**
     * Create an instance of {@link AssessmentPeriodReferenceType }
     * 
     */
    public AssessmentPeriodReferenceType createAssessmentPeriodReferenceType() {
        return new AssessmentPeriodReferenceType();
    }

    /**
     * Create an instance of {@link AssessmentItem }
     * 
     */
    public AssessmentItem createAssessmentItem() {
        return new AssessmentItem();
    }

    /**
     * Create an instance of {@link StudentTitleIPartAProgramAssociation }
     * 
     */
    public StudentTitleIPartAProgramAssociation createStudentTitleIPartAProgramAssociation() {
        return new StudentTitleIPartAProgramAssociation();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AssessmentResult }
     * 
     */
    public AssessmentResult createAssessmentResult() {
        return new AssessmentResult();
    }

    /**
     * Create an instance of {@link LearningObjectiveIdentityType }
     * 
     */
    public LearningObjectiveIdentityType createLearningObjectiveIdentityType() {
        return new LearningObjectiveIdentityType();
    }

    /**
     * Create an instance of {@link GradeLevelsType }
     * 
     */
    public GradeLevelsType createGradeLevelsType() {
        return new GradeLevelsType();
    }

    /**
     * Create an instance of {@link ProgramParticipation }
     * 
     */
    public ProgramParticipation createProgramParticipation() {
        return new ProgramParticipation();
    }

    /**
     * Create an instance of {@link ObjectiveAssessmentReferenceType }
     * 
     */
    public ObjectiveAssessmentReferenceType createObjectiveAssessmentReferenceType() {
        return new ObjectiveAssessmentReferenceType();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link ElectronicMail }
     * 
     */
    public ElectronicMail createElectronicMail() {
        return new ElectronicMail();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PerformanceLevelIdentityType }
     * 
     */
    public PerformanceLevelIdentityType createPerformanceLevelIdentityType() {
        return new PerformanceLevelIdentityType();
    }

    /**
     * Create an instance of {@link TeacherSchoolAssociation }
     * 
     */
    public TeacherSchoolAssociation createTeacherSchoolAssociation() {
        return new TeacherSchoolAssociation();
    }

    /**
     * Create an instance of {@link InstitutionTelephone }
     * 
     */
    public InstitutionTelephone createInstitutionTelephone() {
        return new InstitutionTelephone();
    }

    /**
     * Create an instance of {@link CohortReferenceType }
     * 
     */
    public CohortReferenceType createCohortReferenceType() {
        return new CohortReferenceType();
    }

    /**
     * Create an instance of {@link Grade }
     * 
     */
    public Grade createGrade() {
        return new Grade();
    }

    /**
     * Create an instance of {@link EducationalOrgReferenceType }
     * 
     */
    public EducationalOrgReferenceType createEducationalOrgReferenceType() {
        return new EducationalOrgReferenceType();
    }

    /**
     * Create an instance of {@link CTEServicesType }
     * 
     */
    public CTEServicesType createCTEServicesType() {
        return new CTEServicesType();
    }

    /**
     * Create an instance of {@link CohortIdentityType }
     * 
     */
    public CohortIdentityType createCohortIdentityType() {
        return new CohortIdentityType();
    }

    /**
     * Create an instance of {@link StaffEducationOrgEmploymentAssociation }
     * 
     */
    public StaffEducationOrgEmploymentAssociation createStaffEducationOrgEmploymentAssociation() {
        return new StaffEducationOrgEmploymentAssociation();
    }

    /**
     * Create an instance of {@link StudentAcademicRecord }
     * 
     */
    public StudentAcademicRecord createStudentAcademicRecord() {
        return new StudentAcademicRecord();
    }

    /**
     * Create an instance of {@link ReportCard }
     * 
     */
    public ReportCard createReportCard() {
        return new ReportCard();
    }

    /**
     * Create an instance of {@link StudentObjectiveAssessment }
     * 
     */
    public StudentObjectiveAssessment createStudentObjectiveAssessment() {
        return new StudentObjectiveAssessment();
    }

    /**
     * Create an instance of {@link GradingPeriodIdentityType }
     * 
     */
    public GradingPeriodIdentityType createGradingPeriodIdentityType() {
        return new GradingPeriodIdentityType();
    }

    /**
     * Create an instance of {@link PerformanceLevelReferenceType }
     * 
     */
    public PerformanceLevelReferenceType createPerformanceLevelReferenceType() {
        return new PerformanceLevelReferenceType();
    }

    /**
     * Create an instance of {@link LearningStandard }
     * 
     */
    public LearningStandard createLearningStandard() {
        return new LearningStandard();
    }

    /**
     * Create an instance of {@link ProgramIdentityType }
     * 
     */
    public ProgramIdentityType createProgramIdentityType() {
        return new ProgramIdentityType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link StudentSchoolAssociation }
     * 
     */
    public StudentSchoolAssociation createStudentSchoolAssociation() {
        return new StudentSchoolAssociation();
    }

    /**
     * Create an instance of {@link Payroll }
     * 
     */
    public Payroll createPayroll() {
        return new Payroll();
    }

    /**
     * Create an instance of {@link StudentCohortAssociation }
     * 
     */
    public StudentCohortAssociation createStudentCohortAssociation() {
        return new StudentCohortAssociation();
    }

    /**
     * Create an instance of {@link Teacher }
     * 
     */
    public Teacher createTeacher() {
        return new Teacher();
    }

    /**
     * Create an instance of {@link Actual }
     * 
     */
    public Actual createActual() {
        return new Actual();
    }

    /**
     * Create an instance of {@link CreditsByCourse }
     * 
     */
    public CreditsByCourse createCreditsByCourse() {
        return new CreditsByCourse();
    }

    /**
     * Create an instance of {@link EducationalOrgIdentityType }
     * 
     */
    public EducationalOrgIdentityType createEducationalOrgIdentityType() {
        return new EducationalOrgIdentityType();
    }

    /**
     * Create an instance of {@link ClassRanking }
     * 
     */
    public ClassRanking createClassRanking() {
        return new ClassRanking();
    }

    /**
     * Create an instance of {@link RestraintEventReasonsType }
     * 
     */
    public RestraintEventReasonsType createRestraintEventReasonsType() {
        return new RestraintEventReasonsType();
    }

    /**
     * Create an instance of {@link LearningObjective }
     * 
     */
    public LearningObjective createLearningObjective() {
        return new LearningObjective();
    }

    /**
     * Create an instance of {@link StudentCTEProgramAssociation }
     * 
     */
    public StudentCTEProgramAssociation createStudentCTEProgramAssociation() {
        return new StudentCTEProgramAssociation();
    }

    /**
     * Create an instance of {@link ProgramReferenceType }
     * 
     */
    public ProgramReferenceType createProgramReferenceType() {
        return new ProgramReferenceType();
    }

    /**
     * Create an instance of {@link CourseLevelCharacteristicsType }
     * 
     */
    public CourseLevelCharacteristicsType createCourseLevelCharacteristicsType() {
        return new CourseLevelCharacteristicsType();
    }

    /**
     * Create an instance of {@link StudentReferenceType }
     * 
     */
    public StudentReferenceType createStudentReferenceType() {
        return new StudentReferenceType();
    }

    /**
     * Create an instance of {@link PerformanceLevel }
     * 
     */
    public PerformanceLevel createPerformanceLevel() {
        return new PerformanceLevel();
    }

    /**
     * Create an instance of {@link AdditionalCredits }
     * 
     */
    public AdditionalCredits createAdditionalCredits() {
        return new AdditionalCredits();
    }

    /**
     * Create an instance of {@link IncidentBehavior }
     * 
     */
    public IncidentBehavior createIncidentBehavior() {
        return new IncidentBehavior();
    }

    /**
     * Create an instance of {@link Credits }
     * 
     */
    public Credits createCredits() {
        return new Credits();
    }

    /**
     * Create an instance of {@link StudentAssessment.PerformanceLevelReference }
     * 
     */
    public StudentAssessment.PerformanceLevelReference createStudentAssessmentPerformanceLevelReference() {
        return new StudentAssessment.PerformanceLevelReference();
    }

    /**
     * Create an instance of {@link SchoolCategoriesType }
     * 
     */
    public SchoolCategoriesType createSchoolCategoriesType() {
        return new SchoolCategoriesType();
    }

    /**
     * Create an instance of {@link SpecialAccommodationsType }
     * 
     */
    public SpecialAccommodationsType createSpecialAccommodationsType() {
        return new SpecialAccommodationsType();
    }

    /**
     * Create an instance of {@link AssessmentItemReferenceType }
     * 
     */
    public AssessmentItemReferenceType createAssessmentItemReferenceType() {
        return new AssessmentItemReferenceType();
    }

    /**
     * Create an instance of {@link GradebookEntry }
     * 
     */
    public GradebookEntry createGradebookEntry() {
        return new GradebookEntry();
    }

    /**
     * Create an instance of {@link SecondaryIncidentBehavior }
     * 
     */
    public SecondaryIncidentBehavior createSecondaryIncidentBehavior() {
        return new SecondaryIncidentBehavior();
    }

    /**
     * Create an instance of {@link SessionReferenceType }
     * 
     */
    public SessionReferenceType createSessionReferenceType() {
        return new SessionReferenceType();
    }

    /**
     * Create an instance of {@link StudentCharacteristic }
     * 
     */
    public StudentCharacteristic createStudentCharacteristic() {
        return new StudentCharacteristic();
    }

    /**
     * Create an instance of {@link DisciplineIncidentIdentityType }
     * 
     */
    public DisciplineIncidentIdentityType createDisciplineIncidentIdentityType() {
        return new DisciplineIncidentIdentityType();
    }

    /**
     * Create an instance of {@link ObjectiveAssessment }
     * 
     */
    public ObjectiveAssessment createObjectiveAssessment() {
        return new ObjectiveAssessment();
    }

    /**
     * Create an instance of {@link StaffIdentityType }
     * 
     */
    public StaffIdentityType createStaffIdentityType() {
        return new StaffIdentityType();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link GraduationPlan }
     * 
     */
    public GraduationPlan createGraduationPlan() {
        return new GraduationPlan();
    }

    /**
     * Create an instance of {@link ObjectiveAssessmentIdentityType }
     * 
     */
    public ObjectiveAssessmentIdentityType createObjectiveAssessmentIdentityType() {
        return new ObjectiveAssessmentIdentityType();
    }

    /**
     * Create an instance of {@link ClassPeriod }
     * 
     */
    public ClassPeriod createClassPeriod() {
        return new ClassPeriod();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ed-fi.org/0100RFC", name = "HispanicLatinoEthnicity", scope = StudentIdentityType.class)
    public JAXBElement<Boolean> createStudentIdentityTypeHispanicLatinoEthnicity(Boolean value) {
        return new JAXBElement<Boolean>(_StudentIdentityTypeHispanicLatinoEthnicity_QNAME, Boolean.class, StudentIdentityType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ed-fi.org/0100RFC", name = "HispanicLatinoEthnicity", scope = StaffIdentityType.class)
    public JAXBElement<Boolean> createStaffIdentityTypeHispanicLatinoEthnicity(Boolean value) {
        return new JAXBElement<Boolean>(_StudentIdentityTypeHispanicLatinoEthnicity_QNAME, Boolean.class, StaffIdentityType.class, value);
    }

}
