//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ed-fi.org/0100RFC", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ed_fi._0100rfc;
