//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The categorization of the circumstances or reason for the restraint. 
 * 
 * <p>Java class for RestraintEventReasonsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RestraintEventReasonsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RetraintEventReason" type="{http://ed-fi.org/0100RFC}RestraintEventReasonItemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestraintEventReasonsType", propOrder = {
    "retraintEventReason"
})
public class RestraintEventReasonsType {

    @XmlElement(name = "RetraintEventReason")
    protected List<RestraintEventReasonItemType> retraintEventReason;

    /**
     * Gets the value of the retraintEventReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retraintEventReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetraintEventReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestraintEventReasonItemType }
     * 
     * 
     */
    public List<RestraintEventReasonItemType> getRetraintEventReason() {
        if (retraintEventReason == null) {
            retraintEventReason = new ArrayList<RestraintEventReasonItemType>();
        }
        return this.retraintEventReason;
    }

}
