//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulates the possible attributes that can be used to lookup the identity of sections at a school.  Two cases are supported:
 *  1. SchoolOrganizationID + UniqueSectionCode
 *  2. SchoolOrganizationID + 
 *       Course (StateCourseCode OR LocalCourseCode) +
 *       Term + ClassPeriod + Location
 * 
 * <p>Java class for SectionIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SectionIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SchoolOrganizationID" type="{http://ed-fi.org/0100RFC}IdentificationCode"/>
 *         &lt;element name="UniqueSectionCode" type="{http://ed-fi.org/0100RFC}UniqueSectionCode" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="CourseCode" type="{http://ed-fi.org/0100RFC}CourseCode"/>
 *           &lt;element name="LocalCourseCode" type="{http://ed-fi.org/0100RFC}LocalCourseCode"/>
 *         &lt;/choice>
 *         &lt;element name="Term" type="{http://ed-fi.org/0100RFC}TermType" minOccurs="0"/>
 *         &lt;element name="ClassPeriodName" type="{http://ed-fi.org/0100RFC}ClassPeriodNameType" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://ed-fi.org/0100RFC}ClassroomIdentificationCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SectionIdentityType", propOrder = {
    "schoolOrganizationID",
    "uniqueSectionCode",
    "courseCode",
    "localCourseCode",
    "term",
    "classPeriodName",
    "location"
})
public class SectionIdentityType {

    @XmlElement(name = "SchoolOrganizationID", required = true)
    protected String schoolOrganizationID;
    @XmlElement(name = "UniqueSectionCode")
    protected String uniqueSectionCode;
    @XmlElement(name = "CourseCode")
    protected CourseCode courseCode;
    @XmlElement(name = "LocalCourseCode")
    protected String localCourseCode;
    @XmlElement(name = "Term")
    protected TermType term;
    @XmlElement(name = "ClassPeriodName")
    protected String classPeriodName;
    @XmlElement(name = "Location")
    protected String location;

    /**
     * Gets the value of the schoolOrganizationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolOrganizationID() {
        return schoolOrganizationID;
    }

    /**
     * Sets the value of the schoolOrganizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolOrganizationID(String value) {
        this.schoolOrganizationID = value;
    }

    /**
     * Gets the value of the uniqueSectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueSectionCode() {
        return uniqueSectionCode;
    }

    /**
     * Sets the value of the uniqueSectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueSectionCode(String value) {
        this.uniqueSectionCode = value;
    }

    /**
     * Gets the value of the courseCode property.
     * 
     * @return
     *     possible object is
     *     {@link CourseCode }
     *     
     */
    public CourseCode getCourseCode() {
        return courseCode;
    }

    /**
     * Sets the value of the courseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseCode }
     *     
     */
    public void setCourseCode(CourseCode value) {
        this.courseCode = value;
    }

    /**
     * Gets the value of the localCourseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalCourseCode() {
        return localCourseCode;
    }

    /**
     * Sets the value of the localCourseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalCourseCode(String value) {
        this.localCourseCode = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link TermType }
     *     
     */
    public TermType getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermType }
     *     
     */
    public void setTerm(TermType value) {
        this.term = value;
    }

    /**
     * Gets the value of the classPeriodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassPeriodName() {
        return classPeriodName;
    }

    /**
     * Sets the value of the classPeriodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassPeriodName(String value) {
        this.classPeriodName = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

}
