//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialEdServiceItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpecialEdServiceItemType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Assistive technology device or service"/>
 *     &lt;enumeration value="Audiological services"/>
 *     &lt;enumeration value="Counseling services"/>
 *     &lt;enumeration value="Early Childhood Intervention program"/>
 *     &lt;enumeration value="Interpreting services"/>
 *     &lt;enumeration value="Medical diagnostic services"/>
 *     &lt;enumeration value="Occupational therapy"/>
 *     &lt;enumeration value="Orientation and mobility training services"/>
 *     &lt;enumeration value="Physical therapy"/>
 *     &lt;enumeration value="Preschool children with disabilities program"/>
 *     &lt;enumeration value="Psychological services"/>
 *     &lt;enumeration value="Recreational services"/>
 *     &lt;enumeration value="Regional Day School Program for the Deaf"/>
 *     &lt;enumeration value="School health services"/>
 *     &lt;enumeration value="Social work services"/>
 *     &lt;enumeration value="Speech therapy"/>
 *     &lt;enumeration value="Transportation service"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpecialEdServiceItemType")
@XmlEnum
public enum SpecialEdServiceItemType {

    @XmlEnumValue("Assistive technology device or service")
    ASSISTIVE_TECHNOLOGY_DEVICE_OR_SERVICE("Assistive technology device or service"),
    @XmlEnumValue("Audiological services")
    AUDIOLOGICAL_SERVICES("Audiological services"),
    @XmlEnumValue("Counseling services")
    COUNSELING_SERVICES("Counseling services"),
    @XmlEnumValue("Early Childhood Intervention program")
    EARLY_CHILDHOOD_INTERVENTION_PROGRAM("Early Childhood Intervention program"),
    @XmlEnumValue("Interpreting services")
    INTERPRETING_SERVICES("Interpreting services"),
    @XmlEnumValue("Medical diagnostic services")
    MEDICAL_DIAGNOSTIC_SERVICES("Medical diagnostic services"),
    @XmlEnumValue("Occupational therapy")
    OCCUPATIONAL_THERAPY("Occupational therapy"),
    @XmlEnumValue("Orientation and mobility training services")
    ORIENTATION_AND_MOBILITY_TRAINING_SERVICES("Orientation and mobility training services"),
    @XmlEnumValue("Physical therapy")
    PHYSICAL_THERAPY("Physical therapy"),
    @XmlEnumValue("Preschool children with disabilities program")
    PRESCHOOL_CHILDREN_WITH_DISABILITIES_PROGRAM("Preschool children with disabilities program"),
    @XmlEnumValue("Psychological services")
    PSYCHOLOGICAL_SERVICES("Psychological services"),
    @XmlEnumValue("Recreational services")
    RECREATIONAL_SERVICES("Recreational services"),
    @XmlEnumValue("Regional Day School Program for the Deaf")
    REGIONAL_DAY_SCHOOL_PROGRAM_FOR_THE_DEAF("Regional Day School Program for the Deaf"),
    @XmlEnumValue("School health services")
    SCHOOL_HEALTH_SERVICES("School health services"),
    @XmlEnumValue("Social work services")
    SOCIAL_WORK_SERVICES("Social work services"),
    @XmlEnumValue("Speech therapy")
    SPEECH_THERAPY("Speech therapy"),
    @XmlEnumValue("Transportation service")
    TRANSPORTATION_SERVICE("Transportation service");
    private final String value;

    SpecialEdServiceItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpecialEdServiceItemType fromValue(String v) {
        for (SpecialEdServiceItemType c: SpecialEdServiceItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
