//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association represents the career and technical education (CTE) program that a student participates in.  The association is an extension of the StudentProgramAssociation particular for CTE programs.
 * 
 * <p>Java class for StudentCTEProgramAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentCTEProgramAssociation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}StudentProgramAssociation">
 *       &lt;sequence>
 *         &lt;element name="CTEProgram" type="{http://ed-fi.org/0100RFC}CTEProgram"/>
 *         &lt;element name="CTEServices" type="{http://ed-fi.org/0100RFC}CTEServicesType" maxOccurs="5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentCTEProgramAssociation", propOrder = {
    "cteProgram",
    "cteServices"
})
public class StudentCTEProgramAssociation
    extends StudentProgramAssociation
{

    @XmlElement(name = "CTEProgram", required = true)
    protected CTEProgram cteProgram;
    @XmlElement(name = "CTEServices")
    protected List<CTEServicesType> cteServices;

    /**
     * Gets the value of the cteProgram property.
     * 
     * @return
     *     possible object is
     *     {@link CTEProgram }
     *     
     */
    public CTEProgram getCTEProgram() {
        return cteProgram;
    }

    /**
     * Sets the value of the cteProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTEProgram }
     *     
     */
    public void setCTEProgram(CTEProgram value) {
        this.cteProgram = value;
    }

    /**
     * Gets the value of the cteServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cteServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCTEServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTEServicesType }
     * 
     * 
     */
    public List<CTEServicesType> getCTEServices() {
        if (cteServices == null) {
            cteServices = new ArrayList<CTEServicesType>();
        }
        return this.cteServices;
    }

}
