//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The competency assessed or evaluated for the student against a specific Learning Objective.
 * 
 * <p>Java class for StudentCompetency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentCompetency">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element name="DiagnosticStatement" type="{http://ed-fi.org/0100RFC}text" minOccurs="0"/>
 *         &lt;element name="StudentSectionAssociationReference" type="{http://ed-fi.org/0100RFC}StudentSectionAssociationReferenceType"/>
 *         &lt;element name="LearningObjectiveReference" type="{http://ed-fi.org/0100RFC}LearningObjectiveReferenceType"/>
 *         &lt;element name="CompetencyLevelReference" type="{http://ed-fi.org/0100RFC}CompetencyLevelReferenceType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentCompetency", propOrder = {
    "diagnosticStatement",
    "studentSectionAssociationReference",
    "learningObjectiveReference",
    "competencyLevelReference"
})
public class StudentCompetency
    extends ComplexObjectType
{

    @XmlElement(name = "DiagnosticStatement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String diagnosticStatement;
    @XmlElement(name = "StudentSectionAssociationReference", required = true)
    protected StudentSectionAssociationReferenceType studentSectionAssociationReference;
    @XmlElement(name = "LearningObjectiveReference", required = true)
    protected LearningObjectiveReferenceType learningObjectiveReference;
    @XmlElement(name = "CompetencyLevelReference", required = true)
    protected CompetencyLevelReferenceType competencyLevelReference;

    /**
     * Gets the value of the diagnosticStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticStatement() {
        return diagnosticStatement;
    }

    /**
     * Sets the value of the diagnosticStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticStatement(String value) {
        this.diagnosticStatement = value;
    }

    /**
     * Gets the value of the studentSectionAssociationReference property.
     * 
     * @return
     *     possible object is
     *     {@link StudentSectionAssociationReferenceType }
     *     
     */
    public StudentSectionAssociationReferenceType getStudentSectionAssociationReference() {
        return studentSectionAssociationReference;
    }

    /**
     * Sets the value of the studentSectionAssociationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentSectionAssociationReferenceType }
     *     
     */
    public void setStudentSectionAssociationReference(StudentSectionAssociationReferenceType value) {
        this.studentSectionAssociationReference = value;
    }

    /**
     * Gets the value of the learningObjectiveReference property.
     * 
     * @return
     *     possible object is
     *     {@link LearningObjectiveReferenceType }
     *     
     */
    public LearningObjectiveReferenceType getLearningObjectiveReference() {
        return learningObjectiveReference;
    }

    /**
     * Sets the value of the learningObjectiveReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningObjectiveReferenceType }
     *     
     */
    public void setLearningObjectiveReference(LearningObjectiveReferenceType value) {
        this.learningObjectiveReference = value;
    }

    /**
     * Gets the value of the competencyLevelReference property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyLevelReferenceType }
     *     
     */
    public CompetencyLevelReferenceType getCompetencyLevelReference() {
        return competencyLevelReference;
    }

    /**
     * Sets the value of the competencyLevelReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyLevelReferenceType }
     *     
     */
    public void setCompetencyLevelReference(CompetencyLevelReferenceType value) {
        this.competencyLevelReference = value;
    }

}
