//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association represents the Title I Part A program(s) that a student participates in or receives services from.  The association is an extension of the StudentProgramAssociation particular for Title I part A programs.
 * 
 * <p>Java class for StudentTitleIPartAProgramAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentTitleIPartAProgramAssociation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}StudentProgramAssociation">
 *       &lt;sequence>
 *         &lt;element name="TitleIPartAParticipant" type="{http://ed-fi.org/0100RFC}TitleIPartAParticipantType"/>
 *         &lt;element name="TitleIPartAServices" type="{http://ed-fi.org/0100RFC}TitleIPartAServicesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TitleIPartASupportServices" type="{http://ed-fi.org/0100RFC}TitleIPartASupportServicesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentTitleIPartAProgramAssociation", propOrder = {
    "titleIPartAParticipant",
    "titleIPartAServices",
    "titleIPartASupportServices"
})
public class StudentTitleIPartAProgramAssociation
    extends StudentProgramAssociation
{

    @XmlElement(name = "TitleIPartAParticipant", required = true)
    protected TitleIPartAParticipantType titleIPartAParticipant;
    @XmlElement(name = "TitleIPartAServices")
    protected List<TitleIPartAServicesType> titleIPartAServices;
    @XmlElement(name = "TitleIPartASupportServices")
    protected List<TitleIPartASupportServicesType> titleIPartASupportServices;

    /**
     * Gets the value of the titleIPartAParticipant property.
     * 
     * @return
     *     possible object is
     *     {@link TitleIPartAParticipantType }
     *     
     */
    public TitleIPartAParticipantType getTitleIPartAParticipant() {
        return titleIPartAParticipant;
    }

    /**
     * Sets the value of the titleIPartAParticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleIPartAParticipantType }
     *     
     */
    public void setTitleIPartAParticipant(TitleIPartAParticipantType value) {
        this.titleIPartAParticipant = value;
    }

    /**
     * Gets the value of the titleIPartAServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleIPartAServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleIPartAServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleIPartAServicesType }
     * 
     * 
     */
    public List<TitleIPartAServicesType> getTitleIPartAServices() {
        if (titleIPartAServices == null) {
            titleIPartAServices = new ArrayList<TitleIPartAServicesType>();
        }
        return this.titleIPartAServices;
    }

    /**
     * Gets the value of the titleIPartASupportServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleIPartASupportServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleIPartASupportServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleIPartASupportServicesType }
     * 
     * 
     */
    public List<TitleIPartASupportServicesType> getTitleIPartASupportServices() {
        if (titleIPartASupportServices == null) {
            titleIPartASupportServices = new ArrayList<TitleIPartASupportServicesType>();
        }
        return this.titleIPartASupportServices;
    }

}
