//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The raw score for the objective assessment for the student.
 * 
 * <p>Java class for StudentObjectiveAssessment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentObjectiveAssessment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element name="RawScoreResult" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ScoreResults" type="{http://ed-fi.org/0100RFC}ScoreResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PerformanceLevelReference" type="{http://ed-fi.org/0100RFC}PerformanceLevelReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StudentTestAssessmentReference" type="{http://ed-fi.org/0100RFC}ReferenceType"/>
 *         &lt;element name="ObjectiveAssessmentReference" type="{http://ed-fi.org/0100RFC}ObjectiveAssessmentReferenceType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentObjectiveAssessment", propOrder = {
    "rawScoreResult",
    "scoreResults",
    "performanceLevelReference",
    "studentTestAssessmentReference",
    "objectiveAssessmentReference"
})
public class StudentObjectiveAssessment
    extends ComplexObjectType
{

    @XmlElement(name = "RawScoreResult")
    protected Integer rawScoreResult;
    @XmlElement(name = "ScoreResults")
    protected List<ScoreResult> scoreResults;
    @XmlElement(name = "PerformanceLevelReference")
    protected List<PerformanceLevelReferenceType> performanceLevelReference;
    @XmlElement(name = "StudentTestAssessmentReference", required = true)
    protected ReferenceType studentTestAssessmentReference;
    @XmlElement(name = "ObjectiveAssessmentReference", required = true)
    protected ObjectiveAssessmentReferenceType objectiveAssessmentReference;

    /**
     * Gets the value of the rawScoreResult property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRawScoreResult() {
        return rawScoreResult;
    }

    /**
     * Sets the value of the rawScoreResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRawScoreResult(Integer value) {
        this.rawScoreResult = value;
    }

    /**
     * Gets the value of the scoreResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scoreResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScoreResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreResult }
     * 
     * 
     */
    public List<ScoreResult> getScoreResults() {
        if (scoreResults == null) {
            scoreResults = new ArrayList<ScoreResult>();
        }
        return this.scoreResults;
    }

    /**
     * Gets the value of the performanceLevelReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the performanceLevelReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerformanceLevelReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PerformanceLevelReferenceType }
     * 
     * 
     */
    public List<PerformanceLevelReferenceType> getPerformanceLevelReference() {
        if (performanceLevelReference == null) {
            performanceLevelReference = new ArrayList<PerformanceLevelReferenceType>();
        }
        return this.performanceLevelReference;
    }

    /**
     * Gets the value of the studentTestAssessmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getStudentTestAssessmentReference() {
        return studentTestAssessmentReference;
    }

    /**
     * Sets the value of the studentTestAssessmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setStudentTestAssessmentReference(ReferenceType value) {
        this.studentTestAssessmentReference = value;
    }

    /**
     * Gets the value of the objectiveAssessmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectiveAssessmentReferenceType }
     *     
     */
    public ObjectiveAssessmentReferenceType getObjectiveAssessmentReference() {
        return objectiveAssessmentReference;
    }

    /**
     * Sets the value of the objectiveAssessmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectiveAssessmentReferenceType }
     *     
     */
    public void setObjectiveAssessmentReference(ObjectiveAssessmentReferenceType value) {
        this.objectiveAssessmentReference = value;
    }

}
