//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association is the StudentProgramAssociation specialization particular for Bilingual programs.  The StudentProgramAssociation represents the program(s) that a student participates in or receives services from.  
 * 
 * <p>Java class for StudentBilingualProgramAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentBilingualProgramAssociation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}StudentProgramAssociation">
 *       &lt;sequence>
 *         &lt;element name="BilingualProgram" type="{http://ed-fi.org/0100RFC}BilingualProgramType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentBilingualProgramAssociation", propOrder = {
    "bilingualProgram"
})
public class StudentBilingualProgramAssociation
    extends StudentProgramAssociation
{

    @XmlElement(name = "BilingualProgram", required = true)
    protected BilingualProgramType bilingualProgram;

    /**
     * Gets the value of the bilingualProgram property.
     * 
     * @return
     *     possible object is
     *     {@link BilingualProgramType }
     *     
     */
    public BilingualProgramType getBilingualProgram() {
        return bilingualProgram;
    }

    /**
     * Sets the value of the bilingualProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link BilingualProgramType }
     *     
     */
    public void setBilingualProgram(BilingualProgramType value) {
        this.bilingualProgram = value;
    }

}
