//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association is the StudentProgramAssociation specialization particular for ESL programs.  The StudentProgramAssociation represents the program(s) that a student participates in or receives services from.  
 * 
 * <p>Java class for StudentESLProgramAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentESLProgramAssociation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}StudentProgramAssociation">
 *       &lt;sequence>
 *         &lt;element name="ESLProgram" type="{http://ed-fi.org/0100RFC}ESLProgramType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentESLProgramAssociation", propOrder = {
    "eslProgram"
})
public class StudentESLProgramAssociation
    extends StudentProgramAssociation
{

    @XmlElement(name = "ESLProgram", required = true)
    protected ESLProgramType eslProgram;

    /**
     * Gets the value of the eslProgram property.
     * 
     * @return
     *     possible object is
     *     {@link ESLProgramType }
     *     
     */
    public ESLProgramType getESLProgram() {
        return eslProgram;
    }

    /**
     * Sets the value of the eslProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESLProgramType }
     *     
     */
    public void setESLProgram(ESLProgramType value) {
        this.eslProgram = value;
    }

}
