//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association represents the supplemental program(s) that a student participates in or receives services from.  The association is an extension of the StudentProgramAssociation particular for supplemental services.
 * 
 * <p>Java class for StudentSupplementalServiceProgramAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentSupplementalServiceProgramAssociation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ed-fi.org/0100RFC}StudentProgramAssociation">
 *       &lt;sequence>
 *         &lt;element name="SupplementalServices" type="{http://ed-fi.org/0100RFC}SupplementalServiceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentSupplementalServiceProgramAssociation", propOrder = {
    "supplementalServices"
})
public class StudentSupplementalServiceProgramAssociation
    extends StudentProgramAssociation
{

    @XmlElement(name = "SupplementalServices", required = true)
    protected List<String> supplementalServices;

    /**
     * Gets the value of the supplementalServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplementalServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplementalServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupplementalServices() {
        if (supplementalServices == null) {
            supplementalServices = new ArrayList<String>();
        }
        return this.supplementalServices;
    }

}
