//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TeachingCredentialType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TeachingCredentialType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Emergency"/>
 *     &lt;enumeration value="Intern"/>
 *     &lt;enumeration value="Master"/>
 *     &lt;enumeration value="Nonrenewable"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Probationary"/>
 *     &lt;enumeration value="Professional"/>
 *     &lt;enumeration value="Provisional"/>
 *     &lt;enumeration value="Regular"/>
 *     &lt;enumeration value="Retired"/>
 *     &lt;enumeration value="Specialist"/>
 *     &lt;enumeration value="Substitute"/>
 *     &lt;enumeration value="TeacherAssistant"/>
 *     &lt;enumeration value="Temporary"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TeachingCredentialType")
@XmlEnum
public enum TeachingCredentialType {

    @XmlEnumValue("Emergency")
    EMERGENCY("Emergency"),
    @XmlEnumValue("Intern")
    INTERN("Intern"),
    @XmlEnumValue("Master")
    MASTER("Master"),
    @XmlEnumValue("Nonrenewable")
    NONRENEWABLE("Nonrenewable"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Probationary")
    PROBATIONARY("Probationary"),
    @XmlEnumValue("Professional")
    PROFESSIONAL("Professional"),
    @XmlEnumValue("Provisional")
    PROVISIONAL("Provisional"),
    @XmlEnumValue("Regular")
    REGULAR("Regular"),
    @XmlEnumValue("Retired")
    RETIRED("Retired"),
    @XmlEnumValue("Specialist")
    SPECIALIST("Specialist"),
    @XmlEnumValue("Substitute")
    SUBSTITUTE("Substitute"),
    @XmlEnumValue("TeacherAssistant")
    TEACHER_ASSISTANT("TeacherAssistant"),
    @XmlEnumValue("Temporary")
    TEMPORARY("Temporary");
    private final String value;

    TeachingCredentialType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TeachingCredentialType fromValue(String v) {
        for (TeachingCredentialType c: TeachingCredentialType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
