//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An indication of what Title I supplemental educational services  received by students within the school during the school year.
 * 
 * <p>Java class for TitleIPartAServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TitleIPartAServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TitleIPartAService" type="{http://ed-fi.org/0100RFC}TitleIPartAServiceItemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TitleIPartAServicesType", propOrder = {
    "titleIPartAService"
})
public class TitleIPartAServicesType {

    @XmlElement(name = "TitleIPartAService")
    protected List<TitleIPartAServiceItemType> titleIPartAService;

    /**
     * Gets the value of the titleIPartAService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleIPartAService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleIPartAService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleIPartAServiceItemType }
     * 
     * 
     */
    public List<TitleIPartAServiceItemType> getTitleIPartAService() {
        if (titleIPartAService == null) {
            titleIPartAService = new ArrayList<TitleIPartAServiceItemType>();
        }
        return this.titleIPartAService;
    }

}
