//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The type of support services offered to students in Title I programs. 
 * 
 * 
 * <p>Java class for TitleIPartASupportServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TitleIPartASupportServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TitleIPartASupportService" type="{http://ed-fi.org/0100RFC}TitleIPartASupportServiceItemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TitleIPartASupportServicesType", propOrder = {
    "titleIPartASupportService"
})
public class TitleIPartASupportServicesType {

    @XmlElement(name = "TitleIPartASupportService")
    protected List<TitleIPartASupportServiceItemType> titleIPartASupportService;

    /**
     * Gets the value of the titleIPartASupportService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleIPartASupportService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleIPartASupportService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleIPartASupportServiceItemType }
     * 
     * 
     */
    public List<TitleIPartASupportServiceItemType> getTitleIPartASupportService() {
        if (titleIPartASupportService == null) {
            titleIPartASupportService = new ArrayList<TitleIPartASupportServiceItemType>();
        }
        return this.titleIPartASupportService;
    }

}
