//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 07:02:50 AM EST 
//


package org.ed_fi._0100rfc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TitleIPartAServiceItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TitleIPartAServiceItemType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Reading"/>
 *     &lt;enumeration value="Mathematics"/>
 *     &lt;enumeration value="Science"/>
 *     &lt;enumeration value="Social Studies"/>
 *     &lt;enumeration value="Homeless Services"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TitleIPartAServiceItemType")
@XmlEnum
public enum TitleIPartAServiceItemType {

    @XmlEnumValue("Reading")
    READING("Reading"),
    @XmlEnumValue("Mathematics")
    MATHEMATICS("Mathematics"),
    @XmlEnumValue("Science")
    SCIENCE("Science"),
    @XmlEnumValue("Social Studies")
    SOCIAL_STUDIES("Social Studies"),
    @XmlEnumValue("Homeless Services")
    HOMELESS_SERVICES("Homeless Services");
    private final String value;

    TitleIPartAServiceItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TitleIPartAServiceItemType fromValue(String v) {
        for (TitleIPartAServiceItemType c: TitleIPartAServiceItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
